In [30]:
#Load Dataset
import pandas as pd
ratings = pd.read_csv('Ratings.csv')

In [4]:
books = pd.read_csv('Books.csv')

C:\Users\chand\AppData\Local\Temp\ipykernel_9040\679519066.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [6]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [7]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [12]:
# book ratings in range from 0 to 10
ratings['Book-Rating'].value_counts()

Book-Rating
0     716109
8     103736
10     78610
7      76457
9      67541
5      50974
6      36924
4       8904
3       5996
2       2759
1       1770
Name: count, dtype: int64

In [25]:
# first merge the datasets 
df = pd.merge(books,ratings,on='ISBN',how = 'left')

In [15]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2.0,0.0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8.0,5.0
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400.0,0.0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676.0,8.0
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,41385.0,0.0

# Data cleaning

In [17]:
df.isnull().sum()

ISBN                      0
Book-Title                0
Book-Author               2
Year-Of-Publication       0
Publisher                 2
Image-URL-S               0
Image-URL-M               0
Image-URL-L               4
User-ID                1209
Book-Rating            1209
dtype: int64

In [18]:
df.dropna(inplace=True)

In [19]:
df.shape

(1031128, 10)

In [27]:
df = df.sample(n=20000,random_state=42).reset_index(drop=True)

In [24]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0688092292,Beware the Naked Man Who Offers You His Shirt,Harvey Mackay,1990,Harpercollins,http://images.amazon.com/images/P/0688092292.0...,http://images.amazon.com/images/P/0688092292.0...,http://images.amazon.com/images/P/0688092292.0...,85280.0,5.0
1,042517400X,"Night Moves (Tom Clancy's Net Force, No. 3)",Tom Clancy,2000,Berkley Publishing Group,http://images.amazon.com/images/P/042517400X.0...,http://images.amazon.com/images/P/042517400X.0...,http://images.amazon.com/images/P/042517400X.0...,103304.0,0.0
2,0451191153,The Fountainhead,Ayn Rand,1996,New American Library,http://images.amazon.com/images/P/0451191153.0...,http://images.amazon.com/images/P/0451191153.0...,http://images.amazon.com/images/P/0451191153.0...,204676.0,10.0
3,0679747699,The One-Room Schoolhouse: Stories About the Bo...,Jim Heynen,1994,Vintage Books USA,http://images.amazon.com/images/P/0679747699.0...,http://images.amazon.com/images/P/0679747699.0...,http://images.amazon.com/images/P/0679747699.0...,165806.0,0.0
4,0679420339,The Tin Drum (Everyman's Library Series),Gunter Grass,1993,Everyman's Library,http://images.amazon.com/images/P/0679420339.0...,http://images.amazon.com/images/P/0679420339.0...,http://images.amazon.com/images/P/0679420339.0...,140000.0,0.0

In [28]:
df.shape

(20000, 10)

In [29]:
df.to_csv('final_df.csv')

In [31]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,1565936973,Central Auditory Processing Disorders: New Per...,Gail D. Chermak,1997,Singular Publishing Group Inc,http://images.amazon.com/images/P/1565936973.0...,http://images.amazon.com/images/P/1565936973.0...,http://images.amazon.com/images/P/1565936973.0...,136139.0,7.0
1,0440200563,Fine Things,Danielle Steel,1988,Dell,http://images.amazon.com/images/P/0440200563.0...,http://images.amazon.com/images/P/0440200563.0...,http://images.amazon.com/images/P/0440200563.0...,242143.0,0.0
2,0684861593,Amy and Isabelle,Elizabeth Strout,0,Simon Schuster Trade,http://images.amazon.com/images/P/0684861593.0...,http://images.amazon.com/images/P/0684861593.0...,http://images.amazon.com/images/P/0684861593.0...,151537.0,0.0
3,1891620487,American Greats,Robert A. Wilson,1999,PublicAffairs,http://images.amazon.com/images/P/1891620487.0...,http://images.amazon.com/images/P/1891620487.0...,http://images.amazon.com/images/P/1891620487.0...,231237.0,10.0
4,2877302962,Bleu presque transparent,RyÃ?Â» Murakami,1999,Philippe Picquier,http://images.amazon.com/images/P/2877302962.0...,http://images.amazon.com/images/P/2877302962.0...,http://images.amazon.com/images/P/2877302962.0...,33943.0,0.0

# Popularity Based Recommendation System

-To implement the popularity based recommendation system using the dataset,the idea is to recommend the most popular based on number of ratings or the average rating score.Here how you can do this

-- Group the dataset by book-title and calculate the average rating and the number of ratings for each book
--sort the books based on either the average rating or the number of ratings
(whichever you defined as popularity).

--Recommend books that have highest popularity score

In [32]:
book_ratings = df.groupby('Book-Title').agg({'Book-Rating':['mean','count']}).reset_index()

In [33]:
book_ratings

                                              Book-Title Book-Rating
                                                                mean count
0                                                   !Yo!         8.0     1
1      'Tis The Season (Harlequin Historical Series, ...         0.0     1
2                  01-01-00: The Novel of the Millennium         8.0     1
3                      0373953194 Christmas Stories 1993         0.0     1
4                                  1,001 Great Pet Jokes         7.0     1
...                                                  ...         ...   ...
15243                      one hundred years of solitude         0.0     1
15244                                           stardust         0.0     1
15245                           Â¿QuÃ© me quieres, amor?         6.0     1
15246  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...         7.0     1
15247                                      Ã?Â?lpiraten.         0.0     1

[15248 rows x 3 columns]

In [35]:
book_ratings.columns = ['Book-Title','Avg-Rating','Number']

In [36]:
book_ratings_sorted = book_ratings.sort_values(by=['Avg-Rating','Number'],ascending=False)

In [39]:
top_books = book_ratings_sorted.head(10)

In [42]:
top_books_final = pd.merge(top_books,df[['Book-Title','Image-URL-M']],on='Book-Title',how='left')

In [43]:
top_books_final

,Book-Title,Avg-Rating,Number,Image-URL-M
0,Night,10.0,4,http://images.amazon.com/images/P/0553272535.0...
1,Night,10.0,4,http://images.amazon.com/images/P/0553272535.0...
2,Night,10.0,4,http://images.amazon.com/images/P/0553272535.0...
3,Night,10.0,4,http://images.amazon.com/images/P/0553272535.0...
4,"All the Pretty Horses (Border Trilogy, Vol 1)",10.0,2,http://images.amazon.com/images/P/0394574745.0...
5,"All the Pretty Horses (Border Trilogy, Vol 1)",10.0,2,http://images.amazon.com/images/P/0394574745.0...
6,Answered Prayers,10.0,2,http://images.amazon.com/images/P/044023672X.0...
7,Answered Prayers,10.0,2,http://images.amazon.com/images/P/0385335431.0...
8,By the Light of the Moon,10.0,2,http://images.amazon.com/images/P/0553582763.0...
9,By the Light of the Moon,10.0,2,http://images.amazon.com/images/P/0553582763.0...
10,Carrie,10.0,2,http://images.amazon.com/images/P/0385086954.0...
11,Carrie,10.0,2,http://images.amazon.com/images/P/0671039725.0...
12,Dune (Remembering Tomorrow),10.0,2,http://images.amazon.com/images/P/0441172717.0...
13,Dune (Remembering Tomorrow),10.0,2,http://images.amazon.com/images/P/0441172717.0...
14,Holes (Newbery Medal Book),10.0,2,http://images.amazon.com/images/P/0374332657.0...
15,Holes (Newbery Medal Book),10.0,2,http://images.amazon.com/images/P/0374332657.0...
16,It's Always Something,10.0,2,http://images.amazon.com/images/P/0671638688.0...
17,It's Always Something,10.0,2,http://images.amazon.com/images/P/0380710722.0...
18,Politically Correct Holiday Stories: For an En...,10.0,2,http://images.amazon.com/images/P/0028604202.0...
19,Politically Correct Holiday Stories: For an En...,10.0,2,http://images.amazon.com/images/P/0028604202.0...
20,Silent Prey,10.0,2,http://images.amazon.com/images/P/0425137562.0...
21,Silent Prey,10.0,2,http://images.amazon.com/images/P/0425137562.0...

In [49]:
final_books_recommend = top_books_final.drop_duplicates(['Book-Title'])

In [51]:
final_books_recommend.to_csv('final_books_recommend.csv')